apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web
  name: web
  namespace: lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
      tolerations:
      - key: shipay.com.br/capacity-type
        operator: Equal
        value: spot
        effect: NoSchedule
      - key: shipay.com.br/capacity-type
        operator: Equal
        value: ondemand
        effect: NoSchedule